name: Formatting

on:
  push:
    branches:
      - develop

jobs:
  check:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Run Spotless
        run: ./gradlew spotlessCheck
