name: Publishing

on:
  push:
    branches:
      - develop
      - release/*
      - hotfix/*
    tags:
      - v*.*.*

env:
  REGISTRY: ghcr.io

jobs:
  formatting:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Run Spotless
        run: ./gradlew --no-daemon spotlessCheck

  test:
    name: Test
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Build emails
        run: make emails

      - name: Run tests
        run: ./gradlew --no-daemon test
        env:
          MP_JWT_VERIFY_PUBLICKEY: ${{ vars.MP_JWT_VERIFY_PUBLICKEY }}
          SMALLRYE_JWT_SIGN_KEY: ${{ secrets.SMALLRYE_JWT_SIGN_KEY }}
          APP_URL: https://api.fyreplace.example.org
          APP_FRONT_URL: https://fyreplace.example.org
          APP_WEBSITE_URL: https://www.fyreplace.example.org
